name: keepsecretsafe
description: A library to securely access GCP Secret Manager from Flutter applications.
version: 0.1.0

environment:
  sdk: ">=2.12.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  googleapis_auth: ^1.6.0
  logger: ^2.4.0
  mockito: ^5.4.4
  flutter_dotenv: ^5.1.0
  universal_io: ^2.2.2
  google_secret_manager: ^1.1.0

flutter:
  assets:
    - assets/key.json

dev_dependencies:
  flutter_test:
    sdk: flutter
